In [32]:
import numpy as np
import pandas as pd

In [33]:
ds = 'train'
# ds = 'test'
df = pd.read_csv('{}_edited.csv'.format(ds),header=0)

In [34]:
from sklearn import metrics

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier

In [35]:
y = df['Survived'].to_numpy()
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [40]:
X = df[['Pclass','Sex','AgeCategory','SibSp','Parch','Fare','Embarked']].to_numpy()
X

array([[ 3.    ,  1.    ,  2.    , ...,  0.    ,  7.25  ,  3.    ],
       [ 1.    ,  2.    ,  3.    , ...,  0.    , 71.2833,  1.    ],
       [ 3.    ,  2.    ,  2.    , ...,  0.    ,  7.925 ,  3.    ],
       ...,
       [ 3.    ,  2.    ,  0.    , ...,  2.    , 23.45  ,  3.    ],
       [ 1.    ,  1.    ,  2.    , ...,  0.    , 30.    ,  1.    ],
       [ 3.    ,  1.    ,  2.    , ...,  0.    ,  7.75  ,  2.    ]])

In [37]:
model1 = XGBClassifier()
model1.fit(X,y)
df_importance1 = pd.DataFrame(index=['Pclass','Sex','AgeCategory','SibSp','Parch','Fare','Embarked'],data=model1.feature_importances_)
df_importance1

0
Pclass       0.198839
Sex          0.610349
AgeCategory  0.045570
SibSp        0.040828
Parch        0.044703
Fare         0.033028
Embarked     0.026682

In [38]:
model2 = LGBMClassifier()
model2.fit(X,y)
df_importance2 = pd.DataFrame(index=['Pclass','Sex','AgeCategory','SibSp','Parch','Fare','Embarked'],data=model2.feature_importances_)
df_importance2

0
Pclass        127
Sex           135
AgeCategory   332
SibSp         138
Parch         156
Fare         1961
Embarked      143

In [41]:
model3 = RandomForestClassifier()
model3.fit(X,y)
df_importance3 = pd.DataFrame(index=['Pclass','Sex','AgeCategory','SibSp','Parch','Fare','Embarked'],data=model3.feature_importances_)
df_importance3

0
Pclass       0.090912
Sex          0.295631
AgeCategory  0.100142
SibSp        0.062767
Parch        0.052780
Fare         0.358526
Embarked     0.039241

In [54]:
# ds = 'train'
ds = 'test'
df_test = pd.read_csv('{}_edited.csv'.format(ds),header=0)

PassengerId    False
Pclass         False
Sex            False
Age            False
SibSp          False
Parch          False
Fare           False
Embarked       False
AgeCategory    False
dtype: bool

In [55]:
X_test = df_test[['Pclass','Sex','AgeCategory','SibSp','Parch','Fare','Embarked']].to_numpy()
X_test


array([[ 3.    ,  1.    ,  2.    , ...,  0.    ,  7.8292,  2.    ],
       [ 3.    ,  2.    ,  3.    , ...,  0.    ,  7.    ,  3.    ],
       [ 2.    ,  1.    ,  3.    , ...,  0.    ,  9.6875,  2.    ],
       ...,
       [ 3.    ,  1.    ,  3.    , ...,  0.    ,  7.25  ,  3.    ],
       [ 3.    ,  1.    ,  0.    , ...,  0.    ,  8.05  ,  3.    ],
       [ 3.    ,  1.    ,  0.    , ...,  1.    , 22.3583,  1.    ]])

In [64]:
y_pred1 = model1.predict(X_test)
y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)

df_pred = pd.read_csv('gender_submission.csv',header=0)
df_pred['predict1'] = y_pred1
df_pred['predict2'] = y_pred2
df_pred['predict3'] = y_pred3
df_pred['ensemble_prob'] = ((y_pred1 + y_pred2 + y_pred3) / 3)
df_pred['ensemble_pred'] = np.where(df_pred['ensemble_prob'] >= 0.5,1,0)
df_pred

PassengerId  Survived  predict1  predict2  predict3  ensemble_prob  \
0            892         0         0         0         0       0.000000   
1            893         1         1         0         0       0.333333   
2            894         0         0         0         0       0.000000   
3            895         0         0         0         0       0.000000   
4            896         1         1         1         0       0.666667   
..           ...       ...       ...       ...       ...            ...   
413         1305         0         0         0         0       0.000000   
414         1306         1         1         1         1       1.000000   
415         1307         0         0         0         0       0.000000   
416         1308         0         0         0         0       0.000000   
417         1309         0         1         1         1       1.000000   

     ensemble_pred  
0                0  
1                0  
2                0  
3                0  
4                1  
..             ...  
413              0  
414              1  
415              0  
416              0  
417              1  

[418 rows x 7 columns]

In [66]:
matrix = metrics.confusion_matrix(df_pred['Survived'], df_pred['ensemble_pred'], labels=[0,1])
matrix

array([[236,  30],
       [ 32, 120]])

In [67]:
accuracy = metrics.accuracy_score(df_pred['Survived'], df_pred['ensemble_pred'])
precision, recall, f1, support = metrics.precision_recall_fscore_support(df_pred['Survived'], df_pred['ensemble_pred'], labels=[0,1], beta=1, average=None)
auc = metrics.roc_auc_score(df_pred['Survived'], df_pred['ensemble_pred'])

df_score = pd.DataFrame(index=['accuracy','f1','auc'],data=[accuracy,f1[1],auc])
df_score


0
accuracy  0.851675
f1        0.794702
auc       0.838346